image: ruby:2.7

pipelines:
  tags:
    "v*":
      - step:
          name: Push to RubyGems
          deployment: RubyGems
          script:
            - gem install gem-release
            - (umask  077 ; echo $gem_creds | base64 --decode > ~/.gem/credentials)
            - gem release
          artifacts:
            - pkg/**
      - step:
          name: Push to Docker
          deployment: Docker
          script:
            - './docker_deploy.rb'