version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1

jobs:
  "rubocop":
    docker:
      - image: circleci/ruby:2.5-node
    steps:
      - checkout
      - ruby/load-cache
      - ruby/install-deps
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - ruby/save-cache
  "ruby-two-five":
    docker:
      - image: circleci/ruby:2.5
      - image: memcached:1.5-alpine
    steps:
      - checkout
      - ruby/load-cache
      - ruby/install-deps
      - ruby/run-tests
      - ruby/save-cache
  "ruby-two-six":
    docker:
      - image: circleci/ruby:2.6
      - image: memcached:1.5-alpine
    steps:
      - checkout
      - ruby/load-cache
      - ruby/install-deps
      - ruby/run-tests
      - ruby/save-cache
  "ruby-two-seven":
    docker:
      - image: circleci/ruby:2.7
      - image: memcached:1.5-alpine
    steps:
      - checkout
      - ruby/load-cache
      - ruby/install-deps
      - ruby/run-tests
      - ruby/save-cache

workflows:
  version: 2
  rubocop-rspec:
    jobs:
      - rubocop
      - ruby-two-five:
          requires:
            - rubocop
      - ruby-two-six:
          requires:
            - ruby-two-five
      - ruby-two-seven:
          requires:
            - ruby-two-five